import type { Metadata } from "next";
import "./globals.css";
import HeaderTop from "@/src/components/HeaderTop";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
          <HeaderTop/>
        {children}
        </body>
    </html>
  );
}
